settings:
  default_wizard_prev_button_label: '< Предыдущая страница'
  default_wizard_next_button_label: 'Следующая страница >'
  default_wizard_start_label: Начало
  default_preview_next_button_label: Предпросмотр
  default_draft_button_label: 'Сохранить черновик'
