field.formatter.settings.commerce_pado_add_to_cart:
  type: field.formatter.settings.commerce_add_to_cart
  mapping:
    add_on_field:
      type: string
      label: 'The field to use for add-ons'
    multiple:
      type: boolean
      label: 'To allow multiple add-ons being chosen.'
