commerce_payment.commerce_payment_gateway.plugin.webpay_by_gateway:
  type: commerce_payment_gateway_configuration
  mapping:
    wsb_storeid:
      label: 'Billing ID'
      type: string
    secret_key:
      label: 'Secret key'
      type: string
    wsb_store:
      label: 'The shop name'
      type: string
      nullable: true
    wsb_currency_id:
      label: 'Currency ID'
      type: string
    wsb_return_url:
      label: 'Return URL (Success)'
      type: string
    wsb_cancel_return_url:
      label: 'Return URL (Canceled)'
      type: string
    wsb_language_id:
      label: 'Language ID'
      type: string
