unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: false
element_name: url
time_limit: 0
expire: 300
form_settings:
  user_register_form: true
  user_pass: true
  contact_message_personal_form: true
  node_blog_post_form: false
  node_cta_homepage_form: false
  node_homepage_carousel_slide_form: false
  node_image_gallery_form: false
  node_page_form: false
  node_recipe_form: false
  comment_node_comment_form: true
  comment_product_reviews_form: true
_core:
  default_config_hash: Na6I3vcwFEbSKUmX2JsRKtDmQ_TJkGOEQ6oYSqJvzKA
langcode: ru
